name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true
  prefix:
    description: prefix to use in artifact name
    required: true
  flake:
    description: flake specification
    default: .
  install-path:
    description: path within resulting output, from which to install (e.g. `/bin/foo`)


runs:
  using: composite
  steps:
  - run: nix build -L --show-trace --override-input 'nixify' '.' '${{ inputs.flake }}#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs-nixos#coreutils' -- --coreutils-prog=ginstall -p "./result${{ inputs.install-path }}" '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@v5
    with:
      name: ${{ inputs.prefix }}-${{ inputs.package }}
      path: ${{ inputs.package }}
