name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/cache/rvolosatovs

permissions:
  id-token: write
  contents: read

runs:
  using: composite
  steps:
  - uses: DeterminateSystems/determinate-nix-action@c70cb8ae92d68c66953db28a26a63db1665bc837 # v3.21.5
    with:
      extra-conf: |
        accept-flake-config = true

  - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
    continue-on-error: true
    with:
      name: nixify
      authToken: '${{ inputs.cachixAuthToken }}'
