name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/cache/rvolosatovs

permissions:
  id-token: write
  contents: read

runs:
  using: composite
  steps:
  - uses: DeterminateSystems/determinate-nix-action@v3.9.1
    with:
      extra-conf: |
        accept-flake-config = true

  - uses: cachix/cachix-action@v16
    continue-on-error: true
    with:
      name: nixify
      authToken: '${{ inputs.cachixAuthToken }}'
