[package]
name = "rust-hello-multibin"
version = "0.1.0"
edition = "2021"

[[bin]]
bench = true
name = "hello-other-path"
path = "src/bin/hello.rs"
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
