[package]
name = "rust-bindeps"
version = "0.1.0"
edition = "2021"

[dependencies]
foo = { workspace = true }

[dev-dependencies]
rust-bindeps = { path = "." }

[workspace.dependencies]
foo = { path = "./foo", target = "wasm32-unknown-unknown", artifact = ["cdylib", "bin", "staticlib"] }
