name: update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          revoke: true
      - uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ steps.app-token.outputs.token }}
